@startuml
left to right direction
database "JetStream domain hub" as jshub {
    queue aggregate
}

database "JetStream domain spoke-1" as jsspoke1 {
    queue "test" as test1 
}

database "JetStream domain spoke-2" as jsspoke2 {
    queue "test" as test2 
}

aggregate <--- test1 : source
aggregate <--- test2 : source
@enduml